### ISSUE TITLE
Test Database not creating intentional walks

### ISSUE THREAD

**Issue by benperlman** [sfbrigade/intentional-walk-server#139]
STATEMENT:  INSERT INTO home_intentionalwalk ("event_id", "start", "end", "steps", "pause_time", "distance", "created", "account_id", "device_id") VALUES ('7a0b2d56-09566858-4f640700-cb0288b1', '2023-03-13 11:23:29 (UTC)', '2023-03-13 13:03:16 (UTC)', 2268, 0.000000, 1.587600, '2023-03-13 13:03:16 (UTC)', 87, 'e4b5f5f7');

ERROR:  null value in column "walk_time" violates not-null constraint

DETAIL:  Failing row contains (15153, 59d6f8a3-52c78085-c0371d5c-3e5191db, 2023-03-13 21:19:31+00, 2023-03-14 00:25:48+00, 3871, 0, 2.7097, 2023-03-14 00:25:48+00, 34, 6d61fa9d, null).

I think /scripts/dummydata.py needs to be updated to add the walk_time field

**Comment by francisli** [comment]
Hmm, the model should be automatically calculating and setting walk_time when a record is saved. But maybe the generator script is bypassing the model and inserting directly into the database? I'll look into it...
