### ISSUE TITLE
Age distribution graph

### ISSUE THREAD

**Issue by odo-sfct** [sfbrigade/intentional-walk-server#205]
<img width="880" alt="image" src="https://github.com/sfbrigade/intentional-walk-server/assets/161795448/1082da14-1774-425a-bc90-e2236bc2243c">

The frontend client when selecting "contest_id" is still sending the contest start and end date into the API:
<img width="467" alt="image" src="https://github.com/sfbrigade/intentional-walk-server/assets/161795448/7456b2be-6727-47d4-85fb-3607191a7d8a">

This causes a 422 as contest_id and start_end_date are mutually exclusive.

We'll need to ensure the parameters sent to the API are sanitized by maintaining this mutual exclusivity before sending to the API.

<img width="763" alt="image" src="https://github.com/sfbrigade/intentional-walk-server/assets/161795448/6a2215b6-2d10-42fa-b06c-a9db0107dde8">

In the front end client code (on React), if `contest_id` is not null, the API should not send (start/end date) and vice versa.
You can maintain both in state, so that when a user unchecks, the old state still remains, but the API for the age histogram should not be using both.

**Comment by aukeller** [comment]
I'll start working on this now
