### ISSUE TITLE
Admin should see stats properly de-duped...

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk-server#22]
In the API calls, we've got the logic to de-dupe records across multiple accounts registered to the same address.

We need to make sure that the aggregate stats do this as well, or we'll be double/triple counting steps/distance...

Should we have a background job that does this on a regular interval and stores the states back in the database, rather than doing it on request?

**Comment by abhay1** [comment]
Should be addressed by https://github.com/sfbrigade/intentional-walk-server/pull/25
